# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# On merge from a pull request, bump the version and publish

name: Publish

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
  push:
    branches:
      - develop

permissions:
  pull-requests: read
  contents: write

jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      NPM_TOKEN: ${{secrets.NPM_AUTO_ADAM}}
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Load source
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get files from LFS
        run: git lfs checkout
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm i

      # Always run tests, no matter the source of the push
      - run: npm run test

      # Parse pushed commit messages
      - name: Find out what version bump is needed
        id: version-bump-type
        uses: actions/github-script@v4
        with:
          result-encoding: string
          # TODO: Create as full action with separated out code.
          # TODO: Allow commits to specify a bump with e.g. BUMPS?: (major|minor|patch)
          script: |
            const bumpTypes = {
              minor: ['feat','feature','deps','dependency','dependencies'],
              patch: ['fix','bugfix','perf','performance','docs']
            };
            const allBumpTypes = [...bumpTypes.minor, ...bumpTypes.patch];
            console.log({commits: context.payload.commits});
            const messages = context.payload.commits.map(c=>c.message);
            console.log({messages});
            // based on the commit types, choose the appropriate bump
            const hasBreaking =
              messages.some(m=>m.match(/\bBREAK(ING|S)?\b/)) ||
              messages.some(m=>m.match(new RegExp(`^(${allBumpTypes.join('|')})!:`)));
            // work down from major -> patch, with early returns
            if(hasBreaking){ return 'major'; }
            const types = messages.map(m=>{
              const match = m.match(/^(.+?):/);
              return match && match[1];
            }).filter(x=>x);
            const explicit = messages.map(m=>{
              const bumpMatch = m.match(/\bbumps?: ?(major|minor|patch)\b/i);
              return bumpMatch && bumpMatch[1];
            }).filter(x=>x);
            if(explicit.includes('major')){
              return 'major';
            }
            if(types.some(type=>bumpTypes.minor.includes(type)) || explicit.includes('minor')){
              return 'minor'
            }
            if(types.some(type=>bumpTypes.patch.includes(type)) || explicit.includes('patch')){
              return 'patch'
            }
            return 'skip'

      - name: Store bump version type as env var BUMP
        run: echo "BUMP=${{steps.version-bump-type.outputs.result}}" >> $GITHUB_ENV
      
      - name: Prep GitHub with the actor's info
        run: git config user.email "${{github.event.pusher.email}}"; git config user.name "${{github.event.pusher.name}}";

      - name: Bump the version & push the version commit
        if: ${{ env.BUMP != 'skip'}}
        run: "npm version $BUMP"

      - name: Publish to NPM
        if: ${{ env.BUMP != 'skip'}}
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && npm publish
